name: hola-mundo #Nombre del workflow
run-name: I'm learning GitHub Actions!
on: [push] #evento que lo activará
jobs: #Definición de los jobs
  hola-mundo: #Nombre del job
    runs-on: ubuntu-latest #Maquina en la que correrá
    steps: #Lista de steps del job hola-mundo
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Public IP #Nombre del step
        id: ip #identificador usable dentro del job para otros steps
        uses: haythem/public-ip@v1.3 #Usará el action haythem/public-ip
      - name: Hola mundo #Segundo step de nombre Hola mundo
        run: echo ¡Hola Mundo desde ${{ steps.ip.outputs.ipv4 }}! #bash
      - name: Run index
        run: node index.js
