name: set-new-version
run-name: Set new version when merging into the main branch
on:
  push:
    branches: [main]
jobs:
  new-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Run index
        run: npm version patch
